# Site settings
title: Teaching English Through Literature 
email: tetldmitry@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
Teaching English and Russian grammar, speaking, listening, pronunciation, writing, preparing for tests or exams on literary contexts in class and online.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  dmi7511
google_username: tetldmitry 
permalink: /:categories/:title 
links:
- title: about 
  url: /about
- title: skills
  url: /skills 
- title: resources 
  url: /resources 
- title: hire me 
  url: /hire-me 
# Build settings
markdown: kramdown
